// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI tasks (migrate / studio) use the DIRECT (non-pooled) connection.
    // On Supabase that is the 5432 connection; pgbouncer (6543) is only for runtime.
    // Falls back to DATABASE_URL if a direct URL isn't configured.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
