// Rebuilds the public gallery from the originals you drop in /public/gallery/.
//
// Usage:  node scripts/build-gallery.mjs
//
// - Reads every image in /public/gallery/ (jpg/png/heic/…), the "source of truth".
// - Writes an optimised web copy to /public/gallery/web/<name>.jpg (max 2000px, q82)
//   using macOS `sips` (so HEIC/large photos display + load fast on the web).
// - Deletes web copies whose original was removed, and regenerates lib/gallery.ts.
//
// The full-size originals stay on disk but are git-ignored; only /public/gallery/web/
// (and this list) are committed. Re-run this whenever you add or remove photos.

import { readdirSync, statSync, existsSync, mkdirSync, unlinkSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";

const GALLERY_DIR = "public/gallery";
const WEB_DIR = path.join(GALLERY_DIR, "web");
const LIST = "lib/gallery.ts";
const IMG_RE = /\.(jpe?g|png|webp|gif|avif|heic)$/i;

mkdirSync(WEB_DIR, { recursive: true });

// 1. Current originals (top-level images in /public/gallery/, excluding web/).
const originals = readdirSync(GALLERY_DIR)
  .filter((f) => IMG_RE.test(f))
  .sort();

// Desired web copies: <original stem>.jpg  → gives each photo a stable URL.
const desired = new Map(); // webName -> originalPath
for (const f of originals) {
  const stem = f.replace(/\.[^.]+$/, "");
  desired.set(`${stem}.jpg`, path.join(GALLERY_DIR, f));
}

// 2. Convert (skip if the web copy is already up to date).
let converted = 0;
for (const [webName, srcPath] of desired) {
  const outPath = path.join(WEB_DIR, webName);
  if (existsSync(outPath) && statSync(outPath).mtimeMs >= statSync(srcPath).mtimeMs) continue;
  execFileSync(
    "sips",
    ["-s", "format", "jpeg", "-s", "formatOptions", "82", "-Z", "2000", srcPath, "--out", outPath],
    { stdio: "ignore" },
  );
  converted++;
}

// 3. Remove orphaned web copies (original deleted, or old naming scheme).
let removed = 0;
for (const f of readdirSync(WEB_DIR)) {
  if (!/\.jpg$/i.test(f)) continue;
  if (!desired.has(f)) {
    unlinkSync(path.join(WEB_DIR, f));
    removed++;
  }
}

// 4. Regenerate lib/gallery.ts from the final web/ contents.
const finalWeb = readdirSync(WEB_DIR)
  .filter((f) => /\.jpg$/i.test(f))
  .sort();
const entries = finalWeb
  .map((f, i) => `  { src: "/gallery/web/${f}", alt: "Dance Fit with Emily class photo ${i + 1}" },`)
  .join("\n");
const out = `export type GalleryPhoto = { src: string; alt: string };

// Auto-generated by scripts/build-gallery.mjs from the originals in /public/gallery/.
// To change the gallery: add/remove photos in /public/gallery/, then run:
//   node scripts/build-gallery.mjs
export const GALLERY: GalleryPhoto[] = [
${entries}
];
`;
writeFileSync(LIST, out);

console.log(
  `gallery rebuilt: ${finalWeb.length} photos (${originals.length} originals; ` +
    `${converted} converted, ${removed} orphan web copies removed)`,
);
